# Generated by Django 3.2.11 on 2022-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.CharField(default='photo', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=25),
        ),
    ]
