# Generated by Django 3.2.11 on 2022-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=50)),
                ('class_code', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
