# Generated by Django 3.2.11 on 2022-06-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_course_shedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='grade',
            new_name='grade_code',
        ),
    ]
