# Generated by Django 3.2.11 on 2022-06-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220619_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_shedule',
            name='course_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='course_shedule',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
