# Generated by Django 3.2.11 on 2022-06-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20220619_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_shedule',
            old_name='class_code',
            new_name='grade_code',
        ),
    ]
