# Generated by Django 3.2.11 on 2022-06-20 03:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_shedule',
            name='course_books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='course_shedule',
            name='course_content',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
