# Generated by Django 3.2.11 on 2022-06-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_quiz_assignment_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='t_marks',
        ),
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='type',
        ),
    ]
