# Generated by Django 3.2.11 on 2022-06-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20220620_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quiz_assignment',
        ),
    ]
