# Generated by Django 3.2.11 on 2022-06-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_delete_quiz_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='assignment', max_length=550)),
            ],
        ),
    ]
