# Generated by Django 3.2.11 on 2022-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_quiz_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_assignment',
            name='content',
            field=models.CharField(default='Name : ', max_length=500),
        ),
        migrations.AddField(
            model_name='quiz_assignment',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz_assignment',
            name='syllabus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz_assignment',
            name='t_marks',
            field=models.IntegerField(default=10),
        ),
    ]
