# Generated by Django 3.2.11 on 2022-06-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20220620_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
