# Generated by Django 3.2.11 on 2022-06-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_quiz_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_assignment',
            name='title',
            field=models.CharField(default='assignment 1', max_length=500),
        ),
    ]
