# Generated by Django 3.2.11 on 2022-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_quiz_assignment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_assignment',
            name='course',
            field=models.CharField(default='MTH101', max_length=100),
        ),
    ]
