# Generated by Django 3.2.11 on 2022-06-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_quiz_assignment_result_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='result',
        ),
        migrations.RemoveField(
            model_name='quiz_assignment',
            name='result_remark',
        ),
    ]
