# Generated by Django 3.2.13 on 2022-06-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_quiz_assignment_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
