# Generated by Django 3.2.13 on 2022-07-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_assignment',
            name='assignment_id',
            field=models.CharField(default='01', max_length=500),
        ),
    ]
