# Generated by Django 3.2.13 on 2022-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20220712_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_assignment',
            name='t_marks',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
