# Generated by Django 3.2.13 on 2022-07-13 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_alter_quiz_assignment_t_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='q_marks',
        ),
        migrations.AddField(
            model_name='profile',
            name='result',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='-', max_length=200), blank=True, null=True, size=3), blank=True, null=True, size=100),
        ),
        migrations.AddField(
            model_name='quiz_assignment',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
    ]
